#!/bin/bash

function print_usage() {
    echo "A tool to upload changed files to FTP server."
    echo "$0 SERVER USER PASSWORD WORKING_DIR FILE_LIST REMOTE_DIR"
    echo "SERVER: FTP server"
    echo "USER: FTP user name"
    echo "PASSWORD: FTP password"
    echo "WORKING_DIR: The directory contains the files in FILE_LIST_FILE"
    echo "FILE_LIST: a file contains the changed file list generated by a tool, e.g. git diff"
    echo "REMOTE_DIR: the target remote directory"
}

if [ $# != 6 ]
then
    print_usage
    exit 1
fi

SERVER=$1
USER=$2
PASSWORD=$3
WORKING_DIR=$4
FILE_LIST=$5
REMOTE_DIR=$6

while read file
do
    if [ -e "$file" ]
    then
        cmd="send"
    else
        cmd="delete"
    fi

    echo "$cmd $file"

    ftp -n >~/tmp/upgrade.sh.log 2>&1 <<!
    open "$SERVER"
    user "$USER" "$PASSWORD"
    binary
    prompt
    cd "$REMOTE_DIR"
    lcd "$WORKING_DIR"
    passive
    "$cmd" "$file"
    close
    bye
!

done < "$FILE_LIST"

echo "done"
